### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by BSchoolland** [BSchoolland/v2v-chatbot-api#1]
## Description
Create folders for better organizing this project

## Tasks
- [x] Database Folder - handles all database related stuff and is referenced by other parts of the codebase, from clients managing their plans to chat bots referencing indexed data
- [x] Chatbot API folder - handles communication to and from existing chat bots
- [x] Chatbot Setup API - handles things like setting system prompt, uploading data, and that sort of thing
- [x] webscraping folder - specifically manages the vital data gathering step that allows chat bots to read website data directly
- [x] Dev UI forlder - simple UI for testing APIs and such during development.  
- [x] Other folders as neccesary
