### ISSUE TITLE
[FEAT]: Basic plan selection (free and free 2)

### ISSUE THREAD

**Issue by BSchoolland** [BSchoolland/v2v-chatbot-api#10]
## Description
Basic plan selection with two testing plans.  Temporary development UI

## Tasks
- [x] Plan selection page
- [x] All plans page
- [ ] Plan checkout page
- [x] Plan details page
- [x] Plan editing page
- [x] API for plan checkout
- [x] API for fetching plans
- [x] API for fetching existing plan details
- [x] API for existing plan editing
- [x] API for fetching all plans for a user
