### ISSUE TITLE
[FEAT]: Chatbot Setup

### ISSUE THREAD

**Issue by BSchoolland** [BSchoolland/v2v-chatbot-api#11]
## Description
Create the process by which chat bots will be initially created, from entering the domain to modifying the system prompt.

## Tasks
- [x] "Setup Chatbot" button
- [x] Page with progress bar
- [x] API routes for all actions
