### ISSUE TITLE
Database Setup

### ISSUE THREAD

**Issue by BSchoolland** [BSchoolland/v2v-chatbot-api#2]
## Description
Create all database tables and basic functions for working with the database.

## Tasks
- [x] Create and Entity Relational Diagram (ERD)
- [x] Ensure Docker is correctly configured to allow for a persistent SQLite database
- [x] Create all tables
- [x] Create several simple functions for reading from and modifying key tables to be used later
- [x] Test the basic functions
