### ISSUE TITLE
[FEAT]: Component Delivery

### ISSUE THREAD

**Issue by BSchoolland** [BSchoolland/v2v-chatbot-api#20]
## description
Create a system to deliver the chatbot component to any website

## Tasks:
- [x] Basic js, html, css files
- [x] Routes for getting them
- [x] A way to assign chatbot ids
