### ISSUE TITLE
[REFACTOR]: web scraping code

### ISSUE THREAD

**Issue by BSchoolland** [BSchoolland/v2v-chatbot-api#3]
## Description
The web scraping code works, but is not organized or scalable.  This issue aims to address that.

## tasks: 
- [ ] Separate concerns into different files
- [ ] Create system for running multiple jobs concurrently
- [ ] Create system for load optimization, dynamically adjusting the number of allowed jobs
- [ ] Allow multiple website scraping jobs to be added to the queue at once, with prioritization of manually triggered runs and fair resource splitting between manual jobs.
