### ISSUE TITLE
[Refactor]: Rebuild the chatbot fronted to use best practices

### ISSUE THREAD

**Issue by BSchoolland** [BSchoolland/v2v-chatbot-api#36]
## Description
Last night I wrote a lot of code that could have been better, this issue aims to make sure future development of the chatbot front end is smooth.

## Tasks
- [x] Refactor component.css
- [x] Rethink image loading
- [x] Refactor component.js
- [x] Load suggested questions and starting message from the back end 
- [x] Plan for system where various buttons and chat boxes are allowed
