### ISSUE TITLE
[FEAT]: WordPress plugin

### ISSUE THREAD

**Issue by BSchoolland** [BSchoolland/v2v-chatbot-api#41]
## Description
Create a basic WordPress plugin that allows users to add in the chatbot by pasting the ID rather than by adding custom script tags to every page

## Tasks
- [ ] Settings menu for adding the chatbot id.  
- [ ] Logic for adding script to every page
- [ ] Publish the plugin

## Future
Allow users to manage the chatbot in the plugin itself if we believe WordPress usage could take off.
