### ISSUE TITLE
[CI/CD]: Obtain permanent server for application and automate deployment using github actions

### ISSUE THREAD

**Issue by BSchoolland** [BSchoolland/v2v-chatbot-api#5]
## Description
Buy and set up a hostinger VPS for this API and configure github actions to automatically deploy code pushed to the `main` branch.

## Tasks
- [ ] Get VPS
- [ ] Deploy project on VPS
- [ ] Buy Domain name
- [ ] Configure GitHub actions for automated CI/CD
